### ISSUE TITLE
Too verbose

### ISSUE THREAD

**Issue by thecodingchicken** [worldMachine/TicTacToe#2]
I have a [tic-tac-toe game ](https://github.com/thecodingchicken/tic-tac-toe)by myself, but it isn't in one file like this one either.  Good job.

The point.  You should remove all of the code that prints out:
"""My turn:
anticipating win...move #  5
multiple common win elements
found element not in common elements
anticipating user win...
multiple common win elements
found element not in common elements:  2
moves:  2
moves:  4
moves:  6
moves:  8
"""
That, it seems, is the only thing visible if you run it from the command line or whatever editor you use.

My version has it down with pvp, but the AI can cheat.  Some suggestions?

**Comment by worldMachine** [comment]
Suggestions for your AI? 
I do need to clean this up a lot... good git practice!
